FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0

# install plugin: analysis-kuromoji
RUN bin/elasticsearch-plugin install https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-kuromoji/analysis-kuromoji-7.1.0.zip
