version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch-oss-with-kuromoji:7.1.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # volumes:
    #   - ./elasticsearch/data:/usr/share/elasticsearch/data
    #   - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.0
    container_name: kibana-container
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet

networks:
  esnet: